config/routes.rb
TrainingSchedule::Application.routes.draw do
  resources :phases

  devise_for :users

  root :to => "home#index"

end

app/models/period.rb
class Period
  include Mongoid::Document
  field :number
  field :instructor
  field :location

  belongs_to :week

  validates_presence_of :number

  validates_uniqueness_of :number

  def params
    params = {
      :number => self.number,
      :instructor => self.instructor,
      :location => self.location,
    }
  end
end

app/models/phase.rb
class Phase
  include Mongoid::Document
  field :name
  field :officer

  has_many :weeks, autosave: true
  has_one :qsp

  def params
    params = {
      :officer => self.officer,
    }
    weeks = []
    for week in self.weeks do
      weeks.push(week.params)
    end
    params.merge!({ :weeks => weeks })
  end
end

app/models/qsp.rb
class Qsp
  include Mongoid::Document

  belongs_to :phase, inverse_of: :qsp
  has_many :periods
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""

  validates_presence_of :email
  validates_presence_of :encrypted_password
  
  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String
end

app/models/week.rb
class Week
  include Mongoid::Document
  field :type, type: Symbol
  field :date, type: Date
  field :number, type: Integer

  has_one :period1, :class_name => 'Period', autosave: true
  has_one :period2, :class_name => 'Period', autosave: true
  has_one :period3, :class_name => 'Period', autosave: true

  belongs_to :phase, inverse_of: :weeks

  def params
    params = {
      :period1 => self.period1.params,
      :period2 => self.period2.params,
      :period3 => self.period3.params,
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/phases_controller.rb
class PhasesController < ApplicationController
  # GET /phases
  # GET /phases.json
  def index
    @phases = Phase.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @phases }
    end
  end

  # GET /phases/1
  # GET /phases/1.json
  def show
    @phase = Phase.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @phase }
    end
  end

  # GET /phases/new
  # GET /phases/new.json
  def new
    @phase = Phase.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @phase }
    end
  end

  # GET /phases/1/edit
  def edit
    @phase = Phase.find(params[:id])
  end

  # POST /phases
  # POST /phases.json
  def create
    @phase = Phase.new(params[:phase])

    respond_to do |format|
      if @phase.save
        format.html { redirect_to @phase, notice: 'Phase was successfully created.' }
        format.json { render json: @phase, status: :created, location: @phase }
      else
        format.html { render action: "new" }
        format.json { render json: @phase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /phases/1
  # PUT /phases/1.json
  def update
    @phase = Phase.find(params[:id])

    respond_to do |format|
      if @phase.update_attributes(params[:phase])
        format.html { redirect_to @phase, notice: 'Phase was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @phase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phases/1
  # DELETE /phases/1.json
  def destroy
    @phase = Phase.find(params[:id])
    @phase.destroy

    respond_to do |format|
      format.html { redirect_to phases_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/phases_helper.rb
module PhasesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Training Schedual Planner</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="container">
      <div id="user_nav">
        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path %> |
          <%= link_to "Login", new_user_session_path %>
        <% end %>
      </div>

      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/phases/_form.html.haml
= form_for @phase do |f|
  -if @phase.errors.any?
    #error_explanation
      %h2= "#{pluralize(@phase.errors.count, "error")} prohibited this phase from being saved:"
      %ul
        - @phase.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/phases/edit.html.haml
%h1 Editing phase

= render 'form'

= link_to 'Show', @phase
\|
= link_to 'Back', phases_path

app/views/phases/index.html.haml
%h1 Listing phases

%table
  %tr
    %th Name
    %th
    %th

  - @phases.each do |phase|
    %tr
      %td= phase.name
      %td= link_to 'Show', phase
      %td= link_to 'Edit', edit_phase_path(phase)

%br

= link_to 'New Phase', new_phase_path

app/views/phases/new.html.haml
%h1 New phase

= render 'form'

= link_to 'Back', phases_path

app/views/phases/show.html.haml
%p#notice= notice

.info
  .label
    = @phase.name
  .label
    Officer:
    = @phase.officer

.phase
  - for week in @phase.weeks do
    .week
      .date
        = week.date
      .period
        .label
          Class:
          = week.period1.number
        .label
          Instructor:
          = week.period1.instructor
        .label
          Location:
          = week.period1.location
      .period
        .label
          Class:
          = week.period2.number
        .label
          Instructor:
          = week.period2.instructor
        .label
          Location:
          = week.period2.location
      .period
        .label
          Class:
          = week.period3.number
        .label
          Instructor:
          = week.period3.instructor
        .label
          Location:
          = week.period3.location
.links
  = link_to 'Edit', edit_phase_path(@phase)
  \|
  = link_to 'Back', phases_path